sudo: required
servises:
  - docker

before_install:
  - docker build -t aderihoilya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aderihoilya/react-test npm run test -- --coverage

after_success:
  - docker build -t aderihoilya/multi-client ./client
  - docker build -t aderihoilya/multi-server ./server
  - docker build -t aderihoilya/multi-nginx ./nginx
  - docker build -t aderihoilya/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push aderihoilya/multi-client
  - docker push aderihoilya/multi-server
  - docker push aderihoilya/multi-nginx
  - docker push aderihoilya/multi-worker
